# Generated by Django 3.0.3 on 2020-02-20 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': '用户角色',
                'verbose_name_plural': '用户角色',
                'db_table': 'de_role',
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': '组织信息表',
                'verbose_name_plural': '组织信息表',
                'db_table': 'de_group',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.IntegerField(choices=[(1, '普通用户'), (2, 'VIP'), (3, 'SVIP')], verbose_name='用户类型')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='用户名字')),
                ('password', models.CharField(max_length=64, verbose_name='用户密码')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.UserGroup', verbose_name='用户组织')),
                ('roles', models.ManyToManyField(to='mysite.Role', verbose_name='用户角色')),
            ],
            options={
                'verbose_name': '用户信息表',
                'verbose_name_plural': '用户信息表',
                'db_table': 'de_user',
            },
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, verbose_name='用户令牌')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mysite.UserInfo')),
            ],
            options={
                'verbose_name': '令牌信息表',
                'verbose_name_plural': '令牌信息表',
                'db_table': 'de_token',
            },
        ),
    ]
