# Generated by Django 3.0.3 on 2020-02-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='书名')),
                ('pub_date', models.IntegerField(verbose_name='出版日期')),
                ('bread', models.IntegerField(verbose_name='阅读量')),
                ('bcomment', models.TextField(max_length=256, verbose_name='评论')),
            ],
            options={
                'verbose_name': '书籍',
                'verbose_name_plural': '书籍',
                'db_table': 'books',
            },
        ),
    ]
