# Generated by Django 3.0.3 on 2020-02-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='提示文本:账号不能为空！', max_length=100, verbose_name='姓名')),
                ('sex', models.BooleanField(default=True, verbose_name='性别')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('class_null', models.CharField(max_length=5, verbose_name='班级编号')),
                ('description', models.TextField(verbose_name='个性签名')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
                'db_table': 'tb_student',
            },
        ),
    ]
